# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aa83ae91b76f50dbb90f541065ecea3ef0e6c616470051fe2e2f509682d87f902eaab2da6b5208f913cb98bf353f560d14851f027d478312c8eceafc36cc0c3

test:
  secret_key_base: 4907ef98f3baa62b44806f4e21519b2ebde180a612c9b8d53bdea6f80cb08994829b944eee25b8e8995474cb5ff17b0a5d45522d9d4c3ca4cd7eb190e0fa943b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 682dfff90c1037ca60195b546fcf4f333234773aa3a5aa359100784dc1c73e5f24b8ef0639d202f81e8d9142e18078b7400568f71bb5a18dffccedd5e11f8dd2
